spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sk.bilal.md@gmail.com
spring.mail.password=imqq yuyf oiuz tbsz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.baseUrl=http://localhost:8080

# --- Database Configuration ---
# Using SQLite for local file-based persistence. The test.db file will be created in the project root.
spring.datasource.url=jdbc:sqlite:test.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

server.port=5001

# --- Keycloak Configuration ---
keycloak.server-url=http://localhost:8001
keycloak.realm=master
keycloak.client-id=main_app_server
keycloak.client-secret=OzdRxgGQSY0l9Gaxf0IzjY8QnlXwLVn9

# --- UI Redirect URL
mainapp.url=http://localhost:5001

# --- Loki Config ---
loki.url=http://localhost:3100

# Application Name for Loki tags
app.name=main-app-server

# --- Kafka Configuration ---
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=main-app-group